{% set version = "1.6.0" %}
package:
  name: doctr
  version: {{ version }}

source:
  fn: doctr-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/doctr/doctr-{{ version }}.tar.gz
  sha256: 6683b6635441bd89a7cbaac20ea18804ac5e1ee4cba12e534379b2254dd205f9

build:
  number: 0
  entry_points:
    - doctr = doctr.__main__:main
  skip: true  # [py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - requests
    - cryptography
    - pyyaml

  run:
    - python
    - requests
    - cryptography
    - pyyaml

test:
  imports:
    - doctr

  commands:
    - doctr --help
    - doctr configure --help
    - doctr deploy --help

about:
  home: https://drdoctr.github.io/doctr/index.html
  license: MIT
  summary: 'Deploy docs from Travis to GitHub pages.'

  description: |
    A tool for automatically building docs on Travis CI, and deploying
    them to GitHub pages.
  doc_url: https://drdoctr.github.io/doctr/index.html
  dev_url: https://github.com/drdoctr/doctr

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
    - scopatz
