{% set version = "1.3" %}
package:
  name: doctr
  version: {{ version }}

source:
  fn: doctr-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/doctr/doctr-{{ version }}.tar.gz
  sha256: 14500cfd36492521d3324fe10f0c8a652ae3ca56dec058369319c7ea519a6115

build:
  number: 0
  entry_points:
    - doctr = doctr.__main__:main
  skip: true  # [py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - requests
    - cryptography

  run:
    - python
    - requests
    - cryptography

test:
  imports:
    - doctr

  commands:
    - doctr --help
    - doctr configure --help
    - doctr deploy --help

about:
  home: https://gforsyth.github.io/doctr/docs/
  license: MIT
  summary: 'Deploy docs from Travis to GitHub pages.'

  description: |
    A tool for automatically building Sphinx docs on Travis CI, and deploying
    them to GitHub pages.
  doc_url: https://gforsyth.github.io/doctr/docs/
  dev_url: https://github.com/gforsyth/doctr

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
