travis:
  secure:
    BINSTAR_TOKEN: BeloDDDTpOfnH00v4BNn4w3dlGRgA81AfnsK4Uw7qX8Gyfr5SpWJgt1ZXzXiIE/F7K9DUUzpd5JxOcaatPo4ojZ9VYf/hnAP+eXT2i5OWkeSQjnx+T8kZ1imZV+SiNiO3Gi/YmvYMjPGUIO6h8VrpuaeUhHBFCih7/Y6zjP8I1iJp6ZPZWsoD5aa8wMh3qVwKWQ2poycHDW/LXB8AraLTZ2IWeWDA5UPx5LRFY2SCs7UC6exBS5popJqJ4uKryaM7KqdTM/Nqnp3LcLceU4BJow2M85V+KRrPQGusWtv+DdZlDblkmAZJv6sJOGNN9YJk3r/ujlfFZ/aStHEHGmVNl5ONKmjoOtfrSYiUWjMrza3eJlCcMgI67AiIsFlLNZf7MJZm829hgaw4D0xo3ZaJUhE5xL37Iw5rbLAoLzIG1lM/Ad0lY891TGNYz2zGKk/6Fb5WpCOWUL2aAzMyDiaAL8sfHzCuRyVTLw2mYBsW95SO19DrVndUW57Eh12Eqi2o1xcYnlAADtkp5ebufhEbDSCYI8azc5EHfyMrE7E7x5qMigWslIAVfgWYJvbyw9w1cKk/Ks4hCy0hkXq+9qUBhMU6+6fL4ZyjDvb1NcbA7i4yhPd9ZLdEZv3O0rS/Rp6RRZ30TJKxGtMsGoGR+lIEwOJbrx1KmtDjiycndSVRwM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
